name: COV-MOS-2 Build CI

on:
  push:
    branches:
    - 'master'

jobs:
  Build-Master:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push MASTER
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: uvarc/uva-mos2-ml:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
