name: COV-MOS-2 Build CI

on:
  push:
    branches:
    - 'release'

jobs:
  Build-Release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push MASTER
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: uvarc/uva-mos2-ml:release
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  DCOS-Deployment:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: Build-Release
    steps:
      -
        name: Install awscli
        run: sudo pip install --upgrade pip && pip install awscli
      -
        name: Send SQS message
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body 'static/cvd-mos2'
